### PR TITLE
TEAMROCKET#52: Ingredient Checklist

### PR DESCRIPTION
**Pull request by vchen51**
i went ahead of myself and updated more of the ui/features:
- checklist ingredients functionality added, now should be working correctly
- ~~us customary to metric buttons (note: i added the buttons, but they're a bit weird. some recipes are in us customary and some are in metric, and when use one of the buttons to convert you can't convert back to the original units, which i tried to look into but i think we'd have to do something with local storage or change what we have in the database which may lead to calculation errors, so right now to "reset" you would have to refresh. i.e. if you wanted lbs -> grams you'd press "metric" and if you want it back grams -> lbs you need to refresh the page since the conversion isn't stored)~~
- commented out my measurement buttons, honestly im not too experienced with variable states so im just planning to either scrap it or do it sometime down the road
- navbar changes sizes scrolling
- moved title to navbar for cleanness
- removed the rounded search bar since most elements are not rounded anymore
- added a motto LOL we don't have to keep it i just added it for fun, open to others suggestions too
- changed some padding/margin on every type of page to keep up with the dynamic navbar (note: some pages titles aren't at the same "height" as others bc of the padding, but idk if its enough of an issue to actually fix/notice)
- no more weird resizing for navbar!
- did some updates on the page buttons, added some arrows too

~~there are some (minor?) issues though i couldn't figure out but it's only really regarding the **navbar** when the window size changes or when the website is on mobile. hopefully someone can figure out how bc i spent hours on it and still not sure why the css isn't changing depending on the window width.~~

### CODE REVIEW

**Comment by skmartinelli** [comment]
Hi vanessa, awesome stuff! I'm having bugs with the checkboxes sometimes not functioning and I'm not able to consistently replicate it, going to look into it later and see if I can give any meaningful feedback or make changes myself.

Also right now the site-title href should match the one we have for the logo icon, I think './index.html' 

also mobile needs a lot of clean up but u logged that in your pr

Will leave more comments later but just wanted to log these for now. Wondering if it'd be ok if I pushed whatever small fixes I can figure out to your branch later? I'm not sure how that works lol

**Comment by vchen51** [comment]
> Hi vanessa, awesome stuff ! I'm having bugs with the checkboxes sometimes not functioning and I'm not able to consistently replicate it, going to look into it later and see if I can give any meaningful feedback.
ok i honestly had this problem too but like i thought it was just my vscode bugging 😭 i looked through my code and couldnt find the reason why it would only work when i started up the server so i just assumed it was vscode since it's done stuff like that to me before but ill take a deeper look too!

> Also right now the site-title href should match the one we have for the logo icon, I think './index.html'
for sure 👍 

> and then this may be a personal thing for me but I preferred the previous consistent navbar to the new one. Too much whitespace at the top and also it can cover the recipe title if you scroll slowly. I may be in the wrong here
yeah the reason why i added the dynamic navbar was to include + remove the motto under rocket recipes, but we can definitely take it out and keep it a fixed size if that's what we want overall! and also because i feel like the site was overall very plain so i just wanted to add little changes here and there. i can also remove more of the whitespace ^__^ !

> Will leave more comments later but just wanted to log these for now. Wondering if it'd be ok if I pushed small ui fixes onto your branch later? I'm not sure how sharing branches works lmao
for sure! just lmk what changes if theyre big otherwise go for it

**Comment by gmihir** [comment]
I think I found the issue for the bug where the metric/us buttons aren't always working. The 'current state' of the unit is coming from the stored recipe and not what is on the page, so the button works one way but not the other.

For example, oz -> g conversion means oz is still stored, but g on the page
Then, g -> oz doesn't work because oz is stored so it's not detected as something to switch units when the us button is clicked.

**Comment by vchen51** [comment]
> I think I found the issue for the bug where the metric/us buttons aren't always working. The 'current state' of the unit is coming from the stored recipe and not what is on the page, so the button works one way but not the other.
> 
> For example, oz -> g conversion means oz is still stored, but g on the page Then, g -> oz doesn't work because oz is stored so it's not detected as something to switch units when the us button is clicked.

i was thinking that too, but wouldnt we need to implement local storage? or should i scrap the buttons all together

**Review by gmihir — APPROVED** [review]
This looks great! I might try to work on the buttons on a different branch.

**Review by ahthai2468 — COMMENTED** [review]
Ohhh I like the new motto and transparent back on the favicon. I think having the new smaller navbar (when it shrinks) is a great idea. It starts considering what Sanat was saying about our layout being too open and not prioritizing the recipe cards as much as it should. 

Just a couple side notes:
1. I think the navbar cuts off a bit of the login/signup form background (like the top gets cut off unless you scroll down barely, and then the navbar will shrink and show the entire login/signup form background). If you get the chance, I think it would be nice if the form's entire background is always visible (regardless of whether or not the user decides to scroll down a little). Of course, this isn't a huge deal since users will obviously still see the login/signup prompts in the form regardless of whether or not the choose to scroll down a little. Let me know what you think! I'm not incredibly concerned about this, though.
2. I'm a bit more concerned with how responsive this new navbar is with mobile users. It looks like if the user is on a smaller screen, then they can't see the hamburger menu until they scroll down a bit. And then when they scroll down a bit and click the hamburger menu, the background of the menu is transparent. This will make it difficult for users to read the menu options (since the menu options mesh together with the recipe cards), which is unfortunate. If they're on a tablet-sized screen, then they won't be able to see the entire navbar until they scroll down a bit (before scrolling down, the right side of the navbar gets cut off). Of course, we aren't necessarily exclusively marketing this towards mobile users, so I'm not sure if this is something to spend our time on. But this is something to consider when trying to define our user base since many users do choose to cook from a recipe on their tablet/phone.

Thanks so much for all this, though! Definitely liking the design and improvements, these were the only concerns I had :))

**Review by ahthai2468 — APPROVED** [review]
Looks great, much more mobile responsive! Thanks so much :))

**Pull request merged**
