### PR TITLE
TEAMROCKET #30: Sanitize Inputs

### PR DESCRIPTION
**Pull request by helloserina**
Trying this again? 
- Title must not contain numbers + is trimmed of whitespace
- Summary is trimmed of whitespace
- Recipe servings/amount, readyInMinutes are checked to be integers and does accept inputs that contain integers (converts to integers in this case)
- Ingredient amount must be an integer + trimmed of whitespace
- Ingredient name, units cannot contain numbers + trimmed of whitespace
- Steps are trimmed of whitespace
- The url validation already looks comprehensive so I didn't touch it
- Found a random bug preventing deleting ingredients and steps so I fixed it

DOMPurify is also done, will display an error if necessary, or if the "purified" code is okay, (it probably won't look like code in the end and won't do anything), it will accept. 

Example code that I used as inputs to test:
```
<img src=x onerror=alert(1)//>
<svg><g/onload=alert(2)//<p>
<p>abc<iframe//src=jAva&Tab;script:alert(3)>def</p>
<math><mi//xlink:href="data:x,<script>alert(4)</script>">
<TABLE><tr><td>HELLO</tr></TABL>
<UL><li><A HREF=//google.com>click</UL>
```

### CODE REVIEW

**Review by gmihir — CHANGES_REQUESTED** [review]
These updates look great! However, in the deploy preview, I am having trouble finding any recipes. I think there is an issue with the initial recipe fetch. Let me know if you want any help tracking down the issue!

**Comment by helloserina** [comment]
Oh yeah, there was this thing where I deleted my local storage because we created "corrupted" recipe cards, I'm not sure if that's the cause of the problem but I'll check it out because it was working okay on my end.

**Comment by helloserina** [comment]
Can you send like a screenshot? It's working okay on my end.
Screen Shot 2022-05-30 at 1 55 47 PM
Screen Shot 2022-05-30 at 1 56 29 PM

**Comment by gmihir** [comment]
Can you hop on a quick call? I can show what I see and also why I think it might be happening

**Comment by helloserina** [comment]
Yeah sure https://ucsd.zoom.us/my/serinakhanna

**Comment by helloserina** [comment]
Created new PR. https://github.com/cse112-sp22-group3/rocketrecipes/pull/72

**Pull request closed without merging**
