### PR TITLE
NOTICKET-Integrate Firebase with Personalization

### PR DESCRIPTION
**Pull request by gmihir**
Personalization should now be connected to the database.

### CODE REVIEW

**Review by ahthai2468 — APPROVED** [review]
Seems to be integrated well with firebase

Just a note: Not sure if this is within our scope but I'm noticing that it takes pretty long to load in recipes that fit the user preferences. For example, checking "I'm looking for recipes that are easy to make" and going to the home page will recommend "easy" recipes...but it takes a noticeably long time to load these recommendations. Is this a consequence we are just going to have to accept because of how we integrated firebase?

**Comment by gmihir** [comment]
> Seems to be integrated well with firebase
> 
> Just a note: Not sure if this is within our scope but I'm noticing that it takes pretty long to load in recipes that fit the user preferences. For example, checking "I'm looking for recipes that are easy to make" and going to the home page will recommend "easy" recipes...but it takes a noticeably long time to load these recommendations. Is this a consequence we are just going to have to accept because of how we integrated firebase?

This is partly due to firebase integration + personalization applying to the recommended recipes. I can remove the personalization for recommended recipes if you want.

**Comment by ahthai2468** [comment]
> > Seems to be integrated well with firebase
> > Just a note: Not sure if this is within our scope but I'm noticing that it takes pretty long to load in recipes that fit the user preferences. For example, checking "I'm looking for recipes that are easy to make" and going to the home page will recommend "easy" recipes...but it takes a noticeably long time to load these recommendations. Is this a consequence we are just going to have to accept because of how we integrated firebase?
> 
> This is partly due to firebase integration + personalization applying to the recommended recipes. I can remove the personalization for recommended recipes if you want.

No, I think we should keep personalization for recommended recipes especially since we have fb. I think Sanat will check for a number of user personalization since we decided to continue with firebase, and personalization for recommended recipes will aide in that count.

**Comment by gmihir** [comment]
> > > Seems to be integrated well with firebase
> > > Just a note: Not sure if this is within our scope but I'm noticing that it takes pretty long to load in recipes that fit the user preferences. For example, checking "I'm looking for recipes that are easy to make" and going to the home page will recommend "easy" recipes...but it takes a noticeably long time to load these recommendations. Is this a consequence we are just going to have to accept because of how we integrated firebase?
> > 
> > 
> > This is partly due to firebase integration + personalization applying to the recommended recipes. I can remove the personalization for recommended recipes if you want.
> 
> No, I think we should keep personalization for recommended recipes especially since we have fb. I think Sanat will check for a number of user personalization since we decided to continue with firebase, and personalization for recommended recipes will aide in that count.

Sounds good. If you have time, can you document this reasoning in an ADR? Just to show that we considered the issue. An improvement for future projects would be to use an actual backend and determine recommendations in the cloud instead of on-device when the page loads.

**Comment by DanlandYZ** [comment]
seems like using local storage to buffer `user-preference` works well.

**Review by DanlandYZ — APPROVED** [review]

**Pull request merged**
