### PR TITLE
NO TICKET: Decimal amounts accepted in ingredient amounts

### PR DESCRIPTION
**Pull request by helloserina**

### CODE REVIEW

**Comment by DanlandYZ** [comment]
looks good to me

**Review by DanlandYZ — APPROVED** [review]

**Review by ahthai2468 — APPROVED** [review]
thanks for this! Seems to work on my end

**Comment by helloserina** [comment]
imma make some quick changes before merging! trying to throw an error instead if users use "/"

**Comment by ahthai2468** [comment]
> imma make some quick changes before merging! trying to throw an error instead if users use "/"

as in fractions? I think it would be good as is, it seems to convert "1/2" to "0.5" which I think is a nice thing for users

**Comment by gmihir** [comment]
> > imma make some quick changes before merging! trying to throw an error instead if users use "/"
> 
> as in fractions? I think it would be good as is, it seems to convert "1/2" to "0.5" which I think is a nice thing for users in case they prefer working with fractions over decimals. eval seems to convert it the way we want it to be converted, unless this is a problem?

This was the original implementation, but it seems to require the use of eval(). The eval() function is a big security vulnerability and so we decided against allowing fractions altogether.

**Review by gmihir — DISMISSED** [review]
awesome! one quick thing: seems '(here)' was added to the popup?

noticed this is not there on main so should probably be removed
image

**Pull request merged**
