### PR TITLE
TEAMROCKET #69: Minimize Search Bar

### PR DESCRIPTION
**Pull request by helloserina**
Screen Shot 2022-06-01 at 10 22 53 PM

### CODE REVIEW

**Comment by helloserina** [comment]
fml the tests always pass locally ?? i'll fix this tmr

**Comment by helloserina** [comment]
Hi Vanessa! The larger search bar being the only one on the page is what I intended since Sanat commented about redundancy. Would it be okay if you can fit the navbar? I'm kinda swamped with things rn.

**Comment by ahthai2468** [comment]
Good vibes, yeah Sanat is gonna like this more in the nav bar lol. And conveniently, our frenemy review also had a problem with the size of the original search bar. So two birds one stone

It's probs for the best that you nixed filtering from searching in the nav bar, the UI might get too bulky and troublesome. They can filter once they get to the main search page lol

**Comment by helloserina** [comment]
Yup I removed the filters from the navbar because it's kinda big. I was sort of imaging on like some clothing sites, you need to search a term first before you can apply filtering. Kinda brought that over here too :)

**Comment by skmartinelli** [comment]
My only thing would be to replace the all caps to regular so in the box it says "Start typing..." or you could also copy allrecipes and go "Find a Recipe"

im just intimidated by the all caps haha

**Review by gmihir — CHANGES_REQUESTED** [review]
looks great! one quick thing: please change back the rootUrl in the navigation test.

**Review by gmihir — APPROVED** [review]

**Review by ahthai2468 — APPROVED** [review]

**Pull request merged**
