### PR TITLE
NO-TICKET: Fix negative scaling

### PR DESCRIPTION
**Pull request by skmartinelli**
Set scaled yield and ingredients required to zero if user inputs a negative amount of servings. Forgot to fix when rounding scaling

### CODE REVIEW

**Review by gmihir — CHANGES_REQUESTED** [review]
Looks good! One quick change: please update the text inside the scale box to 0 if the value is negative.

**Comment by skmartinelli** [comment]
Good feedback, thanks Mihir!

**Review by gmihir — APPROVED** [review]

**Comment by gmihir** [comment]
Nice work!

**Review by vchen51 — APPROVED** [review]
looks good!!!

**Pull request merged**
