### PR TITLE
NO-TICKET: Accessibility and mobile UI changes

### PR DESCRIPTION
**Pull request by skmartinelli**
Accessibility changes:
- add lang = en to html header 
- add alt tag to image for screen readers

Mobile UI changes:
- Adjust font size inside cards for smaller cards (Reduces frequency of scroll bars)
- Adjust position of filter button and text so button doesn't overlap with "Sorry no recipes found" when on empty search

### CODE REVIEW

**Comment by vchen51** [comment]
nice adjustments!! i personally feel like the filter button being all the way on the left is a little off-putting, especially since my screen is pretty wide, but might just be me? maybe we can move the filter buttons to be adjacent to the search bar instead?

**Comment by skmartinelli** [comment]
> nice adjustments!! i personally feel like the filter button being all the way on the left is a little off-putting, especially since my screen is pretty wide, but might just be me? maybe we can move the filter buttons to be adjacent to the search bar instead?

Oops yeah good catch @vchen51  just reverted the desktop filter button back to original spot

**Review by lramos0 — APPROVED** [review]
Minimal edits, and looks way better on mobile. Nice!

**Review by ahthai2468 — APPROVED** [review]
vibes :)

**Pull request merged**
